### PR TITLE
Wqp UI branch

### PR DESCRIPTION
**Pull request by lstanish-usgs**
Before making a pull request
----------------------------
- [ ] Make sure all tests run
- [ ] Update the changelog appropriately

User Guide Updates
-----------
- add missing WQX 3.0 domain value lists
- add All_Domains value list
- minor text formatting updates

Description
-----------
WQX user community notified us about missing domain value lists in the User Guide. Furthermore, EPA requested we add a new domain value list, All_Domains.
While making these updates, I cleaned up some inconsistent text and document formatting, which should improve readability.

see JIRA tickets:
- [WQP-1951](https://internal.cida.usgs.gov/jira/browse/WQP-1951)
- [WQP-1952](https://internal.cida.usgs.gov/jira/browse/WQP-1952)

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the JIRA ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by lstanish-usgs** [comment]
@chopkins-usgs could you review the User Guide updates?

**Comment by mbucknell** [comment]
The .Rhistory file should not be committed to the repo.

**Comment by lstanish-usgs** [comment]
> The .Rhistory file should not be committed to the repo.
OK. Tihs hasn't happened in previous commits, not sure why this time is different. How can I fix it?

**Comment by mbucknell** [comment]
On your local machine, you can execute the following to remove the file from the git repo by preserve it on your local machine:
```
git rm --cached server/wqp/markdown/.Rhistory
```
See this for more details: https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

As to how it got committed, you must have added it to to your local .git prior to your last commit. I don't know what tool you are using to manage your local git repo so I can't really be anymore specific then that.

**Comment by lstanish-usgs** [comment]
@mbucknell I kept running into technical difficulties in fixing the .Rhistory file, so started from scratch on my fork. I'd like to discard this PR and do a fresh PR from the fork, is that OK?

**Comment by mbucknell** [comment]
Yep, just use the Close button for the MR

**Comment by lstanish-usgs** [comment]
migrated updates to fork, removing branch

**Pull request closed without merging**
